name: Feature Request
description: Sugerir uma nova funcionalidade
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees:
  - matheusassuncaoo

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova funcionalidade! 

  - type: textarea
    id: problem
    attributes:
      label: Problema/Necessidade
      description: Qual problema esta feature resolveria?
      placeholder: Descreva o problema ou necessidade
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Como você imagina que isso funcionaria?
      placeholder: Descreva sua ideia
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Você considerou outras soluções?
      placeholder: Descreva alternativas

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Quão importante é esta feature para você?
      options:
        - Baixa
        - Média
        - Alta
        - Crítica
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Plataforma
      description: Para qual plataforma é esta feature?
      options:
        - Web
        - Android
        - Ambas
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: Tem algum design ou wireframe?
      placeholder: Cole imagens ou links

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer outra informação relevante
